server:
  port: 9090

#sqlite
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:\JavaCode\WX_Pusher\src\main\resources\db\wx.db
    username: ''
    password: ''
  jpa:
    database-platform: com.dj.sqlite.SqliteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#微信相关配置信息
wx:
  # 接受特殊信息模板的openId
  # 需要注意在 -后面有一个空格，这里是填写special类型的订阅者的openId的地方，有几行就加几个-
  specialOpenIdList:
#   本人
    - omCDf6he14GmHD28eZ250hoAhyZc
#   女朋友
    - omCDf6g-_iKY0zxZQPetq979hOlY
  common:


#chatgpt相关配置
chatgpt:
  model: text-davinci-003
  chat-model: gpt-3.5-turbo
  token: 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
  retries: 10
  proxy-host: 127.0.0.1
  proxy-port: 7890
  session-expiration-time: 30